name: anythinglah
layout_spectrum: 0.7933238606239963
typography_spectrum: 0.5173959178599264
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#B8ECD7'
    - '#083643'
    - '#B1E001'
    - '#CEF09D'
    - '#476C5E'
  brandStrength: 0.9477987573329941
  lightness: 0.06755048848177103
  saturation: 0.3138702034454288
  rhythmicContrast: 0.46351552913309657
title: 'anything, lah'
description: ''
author:
  name: NOAH
  url: anythinglah.com
  email: nospam@anythinglah.com
content_rating:
  adult: false
content: []
github: true
